/* tslint:disable */
/* eslint-disable */
/*
Requisition

Here's our story,

It all began with the frustration of using software that sucks. Prior to starting Keka, our core team was a 100 person business that needed an easy to use software for managing employees. We looked everywhere and all we found were software that was lousy and hard to use. We felt SME businesses in India deserved something better. Something awesome actually!

Thus emerged Keka!

The version of the OpenAPI document: v1


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/

import globalAxios, { AxiosPromise, AxiosInstance, AxiosRequestConfig } from 'axios';
import { Configuration } from '../configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction, isBrowser } from '../common';
import { setOAuthToObject } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
// @ts-ignore
import { ApiLookupPagedResponse } from '../models';
import { paginate } from "../pagination/paginate";
import type * as buffer from "buffer"
import { requestBeforeHook } from '../requestBeforeHook';
/**
 * HolidayCalendarApi - axios parameter creator
 * @export
 */
export const HolidayCalendarApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Get all holidays Calendar
         * @summary Get all holidays Calendar
         * @param {string} [holidaysCalendarIds] The holidaysCalendar ids.
         * @param {number} [pageNumber] 
         * @param {number} [pageSize] Represents how many results you\&#39;d like to retrieve per request (page). Default is 100. Max is 200
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getAllHolidaysCalendar: async (holidaysCalendarIds?: string, pageNumber?: number, pageSize?: number, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/time/holidayscalendar`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions: AxiosRequestConfig = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = configuration && !isBrowser() ? { "User-Agent": configuration.userAgent } : {} as any;
            const localVarQueryParameter = {} as any;

            // authentication oauth2 required
            // oauth required
            await setOAuthToObject(localVarHeaderParameter, "oauth2", [], configuration)
            // authentication oauth2 required
            // oauth required
            await setOAuthToObject(localVarHeaderParameter, "oauth2", [], configuration)
            if (holidaysCalendarIds !== undefined) {
                localVarQueryParameter['holidaysCalendarIds'] = holidaysCalendarIds;
            }

            if (pageNumber !== undefined) {
                localVarQueryParameter['pageNumber'] = pageNumber;
            }

            if (pageSize !== undefined) {
                localVarQueryParameter['pageSize'] = pageSize;
            }


    
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            requestBeforeHook({
                queryParameters: localVarQueryParameter,
                requestConfig: localVarRequestOptions,
                path: localVarPath,
                configuration,
                pathTemplate: '/time/holidayscalendar',
                httpMethod: 'GET'
            });

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * HolidayCalendarApi - functional programming interface
 * @export
 */
export const HolidayCalendarApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = HolidayCalendarApiAxiosParamCreator(configuration)
    return {
        /**
         * Get all holidays Calendar
         * @summary Get all holidays Calendar
         * @param {HolidayCalendarApiGetAllHolidaysCalendarRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getAllHolidaysCalendar(requestParameters: HolidayCalendarApiGetAllHolidaysCalendarRequest = {}, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ApiLookupPagedResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getAllHolidaysCalendar(requestParameters.holidaysCalendarIds, requestParameters.pageNumber, requestParameters.pageSize, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
    }
};

/**
 * HolidayCalendarApi - factory interface
 * @export
 */
export const HolidayCalendarApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = HolidayCalendarApiFp(configuration)
    return {
        /**
         * Get all holidays Calendar
         * @summary Get all holidays Calendar
         * @param {HolidayCalendarApiGetAllHolidaysCalendarRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getAllHolidaysCalendar(requestParameters: HolidayCalendarApiGetAllHolidaysCalendarRequest = {}, options?: AxiosRequestConfig): AxiosPromise<ApiLookupPagedResponse> {
            return localVarFp.getAllHolidaysCalendar(requestParameters, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * Request parameters for getAllHolidaysCalendar operation in HolidayCalendarApi.
 * @export
 * @interface HolidayCalendarApiGetAllHolidaysCalendarRequest
 */
export type HolidayCalendarApiGetAllHolidaysCalendarRequest = {
    
    /**
    * The holidaysCalendar ids.
    * @type {string}
    * @memberof HolidayCalendarApiGetAllHolidaysCalendar
    */
    readonly holidaysCalendarIds?: string
    
    /**
    * 
    * @type {number}
    * @memberof HolidayCalendarApiGetAllHolidaysCalendar
    */
    readonly pageNumber?: number
    
    /**
    * Represents how many results you\'d like to retrieve per request (page). Default is 100. Max is 200
    * @type {number}
    * @memberof HolidayCalendarApiGetAllHolidaysCalendar
    */
    readonly pageSize?: number
    
}

/**
 * HolidayCalendarApiGenerated - object-oriented interface
 * @export
 * @class HolidayCalendarApiGenerated
 * @extends {BaseAPI}
 */
export class HolidayCalendarApiGenerated extends BaseAPI {
    /**
     * Get all holidays Calendar
     * @summary Get all holidays Calendar
     * @param {HolidayCalendarApiGetAllHolidaysCalendarRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof HolidayCalendarApiGenerated
     */
    public getAllHolidaysCalendar(requestParameters: HolidayCalendarApiGetAllHolidaysCalendarRequest = {}, options?: AxiosRequestConfig) {
        return HolidayCalendarApiFp(this.configuration).getAllHolidaysCalendar(requestParameters, options).then((request) => request(this.axios, this.basePath));
    }
}
