/* tslint:disable */
/* eslint-disable */
/*
Requisition

Here's our story,

It all began with the frustration of using software that sucks. Prior to starting Keka, our core team was a 100 person business that needed an easy to use software for managing employees. We looked everywhere and all we found were software that was lousy and hard to use. We felt SME businesses in India deserved something better. Something awesome actually!

Thus emerged Keka!

The version of the OpenAPI document: v1


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/

import globalAxios, { AxiosPromise, AxiosInstance, AxiosRequestConfig } from 'axios';
import { Configuration } from '../configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction, isBrowser } from '../common';
import { setOAuthToObject } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
// @ts-ignore
import { EmployeeLeaveBalanceListItemPagedResponse } from '../models';
import { paginate } from "../pagination/paginate";
import type * as buffer from "buffer"
import { requestBeforeHook } from '../requestBeforeHook';
/**
 * LeaveBalanceApi - axios parameter creator
 * @export
 */
export const LeaveBalanceApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Get all the leave balances
         * @summary Get all Leave balances
         * @param {string} [employeeIds] The employee ids.
         * @param {string} [leaveTypeIds] The leave type ids.
         * @param {number} [pageNumber] 
         * @param {number} [pageSize] Represents how many results you\&#39;d like to retrieve per request (page). Default is 100. Max is 200
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getAllBalances: async (employeeIds?: string, leaveTypeIds?: string, pageNumber?: number, pageSize?: number, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/time/leavebalance`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions: AxiosRequestConfig = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = configuration && !isBrowser() ? { "User-Agent": configuration.userAgent } : {} as any;
            const localVarQueryParameter = {} as any;

            // authentication oauth2 required
            // oauth required
            await setOAuthToObject(localVarHeaderParameter, "oauth2", [], configuration)
            // authentication oauth2 required
            // oauth required
            await setOAuthToObject(localVarHeaderParameter, "oauth2", [], configuration)
            if (employeeIds !== undefined) {
                localVarQueryParameter['employeeIds'] = employeeIds;
            }

            if (leaveTypeIds !== undefined) {
                localVarQueryParameter['leaveTypeIds'] = leaveTypeIds;
            }

            if (pageNumber !== undefined) {
                localVarQueryParameter['pageNumber'] = pageNumber;
            }

            if (pageSize !== undefined) {
                localVarQueryParameter['pageSize'] = pageSize;
            }


    
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            requestBeforeHook({
                queryParameters: localVarQueryParameter,
                requestConfig: localVarRequestOptions,
                path: localVarPath,
                configuration,
                pathTemplate: '/time/leavebalance',
                httpMethod: 'GET'
            });

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * LeaveBalanceApi - functional programming interface
 * @export
 */
export const LeaveBalanceApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = LeaveBalanceApiAxiosParamCreator(configuration)
    return {
        /**
         * Get all the leave balances
         * @summary Get all Leave balances
         * @param {LeaveBalanceApiGetAllBalancesRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getAllBalances(requestParameters: LeaveBalanceApiGetAllBalancesRequest = {}, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<EmployeeLeaveBalanceListItemPagedResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getAllBalances(requestParameters.employeeIds, requestParameters.leaveTypeIds, requestParameters.pageNumber, requestParameters.pageSize, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
    }
};

/**
 * LeaveBalanceApi - factory interface
 * @export
 */
export const LeaveBalanceApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = LeaveBalanceApiFp(configuration)
    return {
        /**
         * Get all the leave balances
         * @summary Get all Leave balances
         * @param {LeaveBalanceApiGetAllBalancesRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getAllBalances(requestParameters: LeaveBalanceApiGetAllBalancesRequest = {}, options?: AxiosRequestConfig): AxiosPromise<EmployeeLeaveBalanceListItemPagedResponse> {
            return localVarFp.getAllBalances(requestParameters, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * Request parameters for getAllBalances operation in LeaveBalanceApi.
 * @export
 * @interface LeaveBalanceApiGetAllBalancesRequest
 */
export type LeaveBalanceApiGetAllBalancesRequest = {
    
    /**
    * The employee ids.
    * @type {string}
    * @memberof LeaveBalanceApiGetAllBalances
    */
    readonly employeeIds?: string
    
    /**
    * The leave type ids.
    * @type {string}
    * @memberof LeaveBalanceApiGetAllBalances
    */
    readonly leaveTypeIds?: string
    
    /**
    * 
    * @type {number}
    * @memberof LeaveBalanceApiGetAllBalances
    */
    readonly pageNumber?: number
    
    /**
    * Represents how many results you\'d like to retrieve per request (page). Default is 100. Max is 200
    * @type {number}
    * @memberof LeaveBalanceApiGetAllBalances
    */
    readonly pageSize?: number
    
}

/**
 * LeaveBalanceApiGenerated - object-oriented interface
 * @export
 * @class LeaveBalanceApiGenerated
 * @extends {BaseAPI}
 */
export class LeaveBalanceApiGenerated extends BaseAPI {
    /**
     * Get all the leave balances
     * @summary Get all Leave balances
     * @param {LeaveBalanceApiGetAllBalancesRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof LeaveBalanceApiGenerated
     */
    public getAllBalances(requestParameters: LeaveBalanceApiGetAllBalancesRequest = {}, options?: AxiosRequestConfig) {
        return LeaveBalanceApiFp(this.configuration).getAllBalances(requestParameters, options).then((request) => request(this.axios, this.basePath));
    }
}
