/*
Requisition

Here's our story,

It all began with the frustration of using software that sucks. Prior to starting Keka, our core team was a 100 person business that needed an easy to use software for managing employees. We looked everywhere and all we found were software that was lousy and hard to use. We felt SME businesses in India deserved something better. Something awesome actually!

Thus emerged Keka!

The version of the OpenAPI document: v1


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { PaymentStatus } from './payment-status';

/**
 * 
 * @export
 * @interface Batch
 */
export interface Batch {
    /**
     * 
     * @type {string}
     * @memberof Batch
     */
    'description'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Batch
     */
    'id'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Batch
     */
    'name'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Batch
     */
    'forPeriod'?: string | null;
    /**
     * 
     * @type {PaymentStatus}
     * @memberof Batch
     */
    'status'?: PaymentStatus;
    /**
     * 
     * @type {string}
     * @memberof Batch
     */
    'paymentFor'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Batch
     */
    'identifier'?: string | null;
}

