/*
Requisition

Here's our story,

It all began with the frustration of using software that sucks. Prior to starting Keka, our core team was a 100 person business that needed an easy to use software for managing employees. We looked everywhere and all we found were software that was lousy and hard to use. We felt SME businesses in India deserved something better. Something awesome actually!

Thus emerged Keka!

The version of the OpenAPI document: v1


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface EducationDTO
 */
export interface EducationDTO {
    /**
     * Gets or sets the degree.
     * @type {string}
     * @memberof EducationDTO
     */
    'degree'?: string | null;
    /**
     * Gets or sets the branch.
     * @type {string}
     * @memberof EducationDTO
     */
    'branch'?: string | null;
    /**
     * Gets or sets the date of joining.
     * @type {string}
     * @memberof EducationDTO
     */
    'dateOfJoining'?: string | null;
    /**
     * Gets or sets the date of completion.
     * @type {string}
     * @memberof EducationDTO
     */
    'dateOfCompletion'?: string | null;
    /**
     * Gets or sets the university.
     * @type {string}
     * @memberof EducationDTO
     */
    'university'?: string | null;
    /**
     * Gets or sets the location.
     * @type {string}
     * @memberof EducationDTO
     */
    'location'?: string | null;
}

