/*
Requisition

Here's our story,

It all began with the frustration of using software that sucks. Prior to starting Keka, our core team was a 100 person business that needed an easy to use software for managing employees. We looked everywhere and all we found were software that was lousy and hard to use. We felt SME businesses in India deserved something better. Something awesome actually!

Thus emerged Keka!

The version of the OpenAPI document: v1


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * Represents a detailed error message for an individual field.
 * @export
 * @interface ErrorDetail
 */
export interface ErrorDetail {
    /**
     * Gets or sets the name of the field that caused the error.
     * @type {string}
     * @memberof ErrorDetail
     */
    'fieldName'?: string | null;
    /**
     * Gets or sets the error message associated with the field.
     * @type {string}
     * @memberof ErrorDetail
     */
    'errorMessage'?: string | null;
}

