/*
Requisition

Here's our story,

It all began with the frustration of using software that sucks. Prior to starting Keka, our core team was a 100 person business that needed an easy to use software for managing employees. We looked everywhere and all we found were software that was lousy and hard to use. We felt SME businesses in India deserved something better. Something awesome actually!

Thus emerged Keka!

The version of the OpenAPI document: v1


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface ExperienceDTO
 */
export interface ExperienceDTO {
    /**
     * Gets or sets the company name.
     * @type {string}
     * @memberof ExperienceDTO
     */
    'companyName'?: string | null;
    /**
     * Gets or sets the designation.
     * @type {string}
     * @memberof ExperienceDTO
     */
    'designation'?: string | null;
    /**
     * Gets or sets a value indicating whether this instance is currently working.
     * @type {boolean}
     * @memberof ExperienceDTO
     */
    'isCurrentlyWorking'?: boolean;
    /**
     * Gets or sets the date of joining.
     * @type {string}
     * @memberof ExperienceDTO
     */
    'dateOfJoining'?: string | null;
    /**
     * Gets or sets the date of relieving.
     * @type {string}
     * @memberof ExperienceDTO
     */
    'dateOfRelieving'?: string | null;
    /**
     * Gets or sets the location.
     * @type {string}
     * @memberof ExperienceDTO
     */
    'location'?: string | null;
}

