/*
Requisition

Here's our story,

It all began with the frustration of using software that sucks. Prior to starting Keka, our core team was a 100 person business that needed an easy to use software for managing employees. We looked everywhere and all we found were software that was lousy and hard to use. We felt SME businesses in India deserved something better. Something awesome actually!

Thus emerged Keka!

The version of the OpenAPI document: v1


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { EducationDTO } from './education-dto';
import { ExperienceDTO } from './experience-dto';
import { Gender } from './gender';
import { JobApplicationDetailsDTO } from './job-application-details-dto';
import { Tag } from './tag';

/**
 * 
 * @export
 * @interface JobCandidateDetailsDTO
 */
export interface JobCandidateDetailsDTO {
    /**
     * 
     * @type {string}
     * @memberof JobCandidateDetailsDTO
     */
    'id'?: string | null;
    /**
     * Gets or sets the first name.
     * @type {string}
     * @memberof JobCandidateDetailsDTO
     */
    'firstName'?: string | null;
    /**
     * Gets or sets the last name.
     * @type {string}
     * @memberof JobCandidateDetailsDTO
     */
    'lastName'?: string | null;
    /**
     * Gets or sets the middle name.
     * @type {string}
     * @memberof JobCandidateDetailsDTO
     */
    'middleName'?: string | null;
    /**
     * 
     * @type {Gender}
     * @memberof JobCandidateDetailsDTO
     */
    'gender'?: Gender;
    /**
     * Gets or sets the email.
     * @type {string}
     * @memberof JobCandidateDetailsDTO
     */
    'email'?: string | null;
    /**
     * Gets or sets the mobile phone.
     * @type {string}
     * @memberof JobCandidateDetailsDTO
     */
    'phone'?: string | null;
    /**
     * Gets or sets the education details.
     * @type {Array<EducationDTO>}
     * @memberof JobCandidateDetailsDTO
     */
    'educationDetails'?: Array<EducationDTO> | null;
    /**
     * Gets or sets the candidate tags
     * @type {Array<Tag>}
     * @memberof JobCandidateDetailsDTO
     */
    'candidateTags'?: Array<Tag> | null;
    /**
     * Gets or sets the experience details.
     * @type {Array<ExperienceDTO>}
     * @memberof JobCandidateDetailsDTO
     */
    'experienceDetails'?: Array<ExperienceDTO> | null;
    /**
     * Gets or sets the skills.
     * @type {Array<string>}
     * @memberof JobCandidateDetailsDTO
     */
    'skills'?: Array<string> | null;
    /**
     * 
     * @type {{ [key: string]: string; }}
     * @memberof JobCandidateDetailsDTO
     */
    'additionalCandidateDetails'?: { [key: string]: string; } | null;
    /**
     * 
     * @type {JobApplicationDetailsDTO}
     * @memberof JobCandidateDetailsDTO
     */
    'jobApplicationDetails'?: JobApplicationDetailsDTO;
    /**
     * 
     * @type {{ [key: string]: string; }}
     * @memberof JobCandidateDetailsDTO
     */
    'archivedDetails'?: { [key: string]: string; } | null;
}

