/*
Requisition

Here's our story,

It all began with the frustration of using software that sucks. Prior to starting Keka, our core team was a 100 person business that needed an easy to use software for managing employees. We looked everywhere and all we found were software that was lousy and hard to use. We felt SME businesses in India deserved something better. Something awesome actually!

Thus emerged Keka!

The version of the OpenAPI document: v1


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { FieldOptionDTO } from './field-option-dto';
import { FieldType } from './field-type';

/**
 * 
 * @export
 * @interface JobApplicationFieldsDTO
 */
export interface JobApplicationFieldsDTO {
    /**
     * Gets or sets the name of the field.
     * @type {string}
     * @memberof JobApplicationFieldsDTO
     */
    'fieldName'?: string | null;
    /**
     * Gets or sets the Field Identifier of the field.
     * @type {string}
     * @memberof JobApplicationFieldsDTO
     */
    'id'?: string | null;
    /**
     * Gets or sets a value indicating whether this !:FieldListItem is required.
     * @type {boolean}
     * @memberof JobApplicationFieldsDTO
     */
    'required'?: boolean;
    /**
     * 
     * @type {FieldType}
     * @memberof JobApplicationFieldsDTO
     */
    'fieldType'?: FieldType;
    /**
     * Gets or sets the field options.
     * @type {Array<FieldOptionDTO>}
     * @memberof JobApplicationFieldsDTO
     */
    'fieldOptions'?: Array<FieldOptionDTO> | null;
}

