/*
Requisition

Here's our story,

It all began with the frustration of using software that sucks. Prior to starting Keka, our core team was a 100 person business that needed an easy to use software for managing employees. We looked everywhere and all we found were software that was lousy and hard to use. We felt SME businesses in India deserved something better. Something awesome actually!

Thus emerged Keka!

The version of the OpenAPI document: v1


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { ErrorDetail } from './error-detail';

/**
 * 
 * @export
 * @interface OkErrorResponse
 */
export interface OkErrorResponse {
    /**
     * Gets or sets the HTTP status code of the response.
     * @type {number}
     * @memberof OkErrorResponse
     */
    'status'?: number;
    /**
     * Gets a value indicating whether the response operation succeeded (HTTP status code within the range of 200 to 299).
     * @type {boolean}
     * @memberof OkErrorResponse
     */
    'succeeded'?: boolean;
    /**
     * Gets or sets the message associated with the response.
     * @type {string}
     * @memberof OkErrorResponse
     */
    'message'?: string | null;
    /**
     * Gets or sets the list of error details for individual fields.
     * @type {Array<ErrorDetail>}
     * @memberof OkErrorResponse
     */
    'errors'?: Array<ErrorDetail> | null;
    /**
     * Gets or sets the error code associated with the error.
     * @type {string}
     * @memberof OkErrorResponse
     */
    'errorCode'?: string | null;
}

