/*
Requisition

Here's our story,

It all began with the frustration of using software that sucks. Prior to starting Keka, our core team was a 100 person business that needed an easy to use software for managing employees. We looked everywhere and all we found were software that was lousy and hard to use. We felt SME businesses in India deserved something better. Something awesome actually!

Thus emerged Keka!

The version of the OpenAPI document: v1


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { EducationDTO } from './education-dto';
import { ExperienceDTO } from './experience-dto';
import { Gender } from './gender';

/**
 * 
 * @export
 * @interface TalentPoolCandidateDTO
 */
export interface TalentPoolCandidateDTO {
    /**
     * 
     * @type {string}
     * @memberof TalentPoolCandidateDTO
     */
    'id'?: string | null;
    /**
     * Gets or sets the first name.
     * @type {string}
     * @memberof TalentPoolCandidateDTO
     */
    'firstName'?: string | null;
    /**
     * Gets or sets the last name.
     * @type {string}
     * @memberof TalentPoolCandidateDTO
     */
    'lastName'?: string | null;
    /**
     * Gets or sets the middle name.
     * @type {string}
     * @memberof TalentPoolCandidateDTO
     */
    'middleName'?: string | null;
    /**
     * 
     * @type {Gender}
     * @memberof TalentPoolCandidateDTO
     */
    'gender'?: Gender;
    /**
     * Gets or sets the email.
     * @type {string}
     * @memberof TalentPoolCandidateDTO
     */
    'email'?: string | null;
    /**
     * Gets or sets the phone
     * @type {string}
     * @memberof TalentPoolCandidateDTO
     */
    'phone'?: string | null;
    /**
     * Gets or sets the education details.
     * @type {Array<EducationDTO>}
     * @memberof TalentPoolCandidateDTO
     */
    'educationDetails'?: Array<EducationDTO> | null;
    /**
     * Gets or sets the experience details.
     * @type {Array<ExperienceDTO>}
     * @memberof TalentPoolCandidateDTO
     */
    'experienceDetails'?: Array<ExperienceDTO> | null;
    /**
     * Gets or sets the skills.
     * @type {Array<string>}
     * @memberof TalentPoolCandidateDTO
     */
    'skills'?: Array<string> | null;
    /**
     * 
     * @type {{ [key: string]: string; }}
     * @memberof TalentPoolCandidateDTO
     */
    'additionalCandidateDetails'?: { [key: string]: string; } | null;
    /**
     * 
     * @type {{ [key: string]: string; }}
     * @memberof TalentPoolCandidateDTO
     */
    'talentPoolDetails'?: { [key: string]: string; } | null;
}

