/*
Requisition

Here's our story,

It all began with the frustration of using software that sucks. Prior to starting Keka, our core team was a 100 person business that needed an easy to use software for managing employees. We looked everywhere and all we found were software that was lousy and hard to use. We felt SME businesses in India deserved something better. Something awesome actually!

Thus emerged Keka!

The version of the OpenAPI document: v1


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { FieldOptionDTO } from './field-option-dto';
import { FieldType } from './field-type';

/**
 * 
 * @export
 * @interface TalentPoolApplicationFieldsDTO
 */
export interface TalentPoolApplicationFieldsDTO {
    /**
     * Gets or sets the name of the field.
     * @type {string}
     * @memberof TalentPoolApplicationFieldsDTO
     */
    'fieldName'?: string | null;
    /**
     * Gets or sets a value indicating whether this Keka.Hire.Core.Entities.Field is required.
     * @type {boolean}
     * @memberof TalentPoolApplicationFieldsDTO
     */
    'required'?: boolean;
    /**
     * 
     * @type {FieldType}
     * @memberof TalentPoolApplicationFieldsDTO
     */
    'fieldType'?: FieldType;
    /**
     * Gets or sets a value indicating whether this field is system generated.
     * @type {boolean}
     * @memberof TalentPoolApplicationFieldsDTO
     */
    'isSystemDefined'?: boolean;
    /**
     * Gets or sets the field options.
     * @type {Array<FieldOptionDTO>}
     * @memberof TalentPoolApplicationFieldsDTO
     */
    'fieldOptions'?: Array<FieldOptionDTO> | null;
    /**
     * Gets or sets the identifier
     * @type {string}
     * @memberof TalentPoolApplicationFieldsDTO
     */
    'id'?: string | null;
}

